apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: nvidia-gpu-operator
  labels:
    argocd.argoproj.io/managed-by: ehs-gitops
spec:
  finalizers:
    - kubernetes
