apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redhat-ods-operator
  namespace: redhat-ods-operator
spec:
  targetNamespaces:
    - redhat-ods-operator
  upgradeStrategy: Default
