apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: redhat-ods-applications
  labels:
    argocd.argoproj.io/managed-by: ehs-gitops
spec:
  finalizers:
    - kubernetes
