apiVersion: dscinitialization.opendatahub.io/v1
kind: DSCInitialization
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: default-dsci
spec:
  applicationsNamespace: redhat-ods-applications
  monitoring:
    managementState: Managed
    namespace: redhat-ods-monitoring
  serviceMesh:
    controlPlane:
      metricsCollection: Istio
      name: data-science-smcp
      namespace: istio-system
    managementState: Removed
  trustedCABundle:
    customCABundle: ''
    managementState: Managed
