apiVersion: v1
kind: Namespace
metadata:
  name: openshift-nfd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: ehs-gitops
spec:
  finalizers:
    - kubernetes
