apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-manifests
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/MoOyeg/quick-argo-test.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}