apiVersion: v1
kind: Namespace
metadata:
  name: gitops-apps
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    openshift.io/cluster-monitoring: "true"
    argocd.argoproj.io/managed-by: ehs-gitops
spec: {}