apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-operators
  namespace: gitops-apps
spec:
  project: default
  source:
    repoURL: https://github.com/MoOyeg/quick-argo-test.git
    targetRevision: HEAD
    path: operator
  destination:
    server: https://kubernetes.default.svc
